### PR TITLE
Allow user to specify font famliy and weight in config.yml

### PR DESCRIPTION
**Pull request by cameronmcefee**
This adds the ability to set the font family and font weight via the `config.yml` file

### CODE REVIEW

**Comment by cameronmcefee** [comment]
I spent about 8 hours today trying to debug why IE9 was giving CSS3111 errors for all of the webfonts generated with this version of things. It turns out that the problem came from the custom font weight. Since custom font weight isn't particularly relevant I've removed it from this pull.

**Comment by puzrin** [comment]
Probably, you used wrong value? For example, instead of css "normal" font uses "Book".

**Comment by puzrin** [comment]
Thank you for updates. Released new version. I've used this project only to prepare fontello's embedded fonts, and didn't tested it carefully for more generic needs.

If you wish to track latest AND tested code, see this file in fontello https://github.com/fontello/fontello/blob/master/server/font/_lib/worker.js#L66

Also note, there is some strange problem with WOFF fonts https://github.com/fontello/fontello/issues/175 . Before switching to this toolchan, i've "fixed" situation by strange hack https://github.com/fontello/font-builder/blob/master/bin/fontbuild.py#L48 . Didn't had time yet to investigate problem deep.

**Comment by cameronmcefee** [comment]
> If you wish to track latest AND tested code, see this file in fontello

Oh that's great. I'll have to look into that. I've been building a simplified font generator on top of svg-font-create to help improve our [currently painful process](If you wish to track latest AND tested code, see this file in fontello) for building Octicons. My generator focuses mostly on making it easy to manage multiple subsets of a single font, but it looks like Fontello may be a good alternative.

> Also note, there is some strange problem with WOFF

I've noticed that issue with the generation of Octicons currently in production (which was build with the last version of Font-Builder). As a work around I've had to call the svg before the woff, otherwise things would break in Chrome on Windows. So far I haven't seen the issue with the latest builds I've been working on that use svg-font-create.

**Comment by puzrin** [comment]
If you need private management for internal needs - fork fontello, update makefile & put your font into submodules. Or, if  Octicons has CC ... / SIL license, i can add it directly to fontello.

Also, you can find useful to study, how separate fonts are created via CLI https://github.com/fontello/fontelico.font

**Pull request merged**
